owner: ollieparsley
repo: interrupt-status

# Add your sites here
sites:
  - name: Don't Interrupt
    url: https://dontinterrupt.app

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.dontinterrupt.app
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://dontinterrupt.app/static/assets/img/logo_single.png
  name: Don't Interrupt Status
  introTitle: ""
  introMessage: This is the Don't Interrupt status page which uses **real-time** data from [Upptime](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: App
      href: https://dontinterrupt.app
